"""Adding isdeleted column

Revision ID: cebfc1029e49
Revises: f24c190c30d4
Create Date: 2021-07-01 20:24:38.178817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebfc1029e49'
down_revision = 'f24c190c30d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel', sa.Column('isDeleted', sa.Boolean(), nullable=False))
    op.add_column('repairs', sa.Column('isDeleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('isDeleted', sa.Boolean(), nullable=False))
    op.add_column('vehicle', sa.Column('isDeleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'isDeleted')
    op.drop_column('users', 'isDeleted')
    op.drop_column('repairs', 'isDeleted')
    op.drop_column('fuel', 'isDeleted')
    # ### end Alembic commands ###
