"""adjusted fuel columns

Revision ID: e856f88fdc2c
Revises: cebfc1029e49
Create Date: 2021-07-04 22:23:55.460073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e856f88fdc2c'
down_revision = 'cebfc1029e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel', sa.Column('total_Qty_purchased_ltrs', sa.Numeric(), nullable=False))
    op.add_column('fuel', sa.Column('total_Qty_purchased_ngn', sa.Numeric(), nullable=False))
    op.add_column('fuel', sa.Column('comments', sa.Text(), nullable=True))
    op.drop_column('fuel', 'total_Qty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel', sa.Column('total_Qty', mysql.DECIMAL(precision=10, scale=0), nullable=False))
    op.drop_column('fuel', 'comments')
    op.drop_column('fuel', 'total_Qty_purchased_ngn')
    op.drop_column('fuel', 'total_Qty_purchased_ltrs')
    # ### end Alembic commands ###
